### ISSUE TITLE
Fix Caterpie male gender rate

### ISSUE THREAD

**Issue by JulianoFdeS** [Rangi42/redstarbluestar#17]
Hi, before start, let me say how I do play Pokémon games, usually, I like to catch every Pokémon in an area before going to other area, while I do this, I like to fight every wild Pokémon to grind.

My problem is in Viridian Forest, I want to catch a MALE caterpie, and I can't find a male at all. It takes around 10-20 minutes to find one, and for some reason, it's ALWAYS female. I have almost 5 hours of playtime, my charmander, nidoran m, rattata, pikachu and beedril are all level 15 because I keep defeating every wild mon that isn't a male caterpie and I feel I'm losing my time playing it. I found like 10 female caterpie, than I lost my patience, I turned ON fast-forwarding and I decided to run battles just to test if I can find a male caterpie faster and NO, it takes 2-5 minutes to find another caterpie and again - female only.

I never had this problem to catch one Pokémon of one specific gender. Even in FRLG that some genders are 75% more common for a few species takes less time to me to find.

I'm really frustrated, and why it's more common pikachu than caterpie? Isn't supposed to be the opposite? I find around 4 pikachu for each caterpie encounter, this doesn't make any sense to me.

I really want to replay this hack (I played it when it gots first release, 2018 IIRC) but this gender rate must be fixed.

**Comment by Rangi42** [comment]
Looks like you just haven't been lucky yet. This was the 10th encounter (after some female Caterpie, and Metapod of both genders):
![image](https://github.com/Rangi42/redstarbluestar/assets/35663410/fdf5168b-74e0-4d17-a476-f5b2e8d41571)
