### ISSUE TITLE
No color for .gbc files?

### ISSUE THREAD

**Issue by mattmills49** [Rangi42/redstarbluestar#4]
I both tried the `.ips` patch as well as making from a local clone and neither roms have color when I open the file using OpenEmu. Any thoughts as to why? I've used multiple `.gbc` roms before that have color using OpenEmu so it could be that but it would be specific to this file. Any help would be much appreciated.

**Comment by aaaaaa123456789** [comment]
As far as I can tell from perusing the makefile, the ROMs are not GBC ROMs. They are instead SGB-compatible DMG ROMs (where DMG is the original Game Boy).
What this means is that playing the games in a GBC would yield monochromatic graphics, just like the original Red and Blue would. Playing the games in a Super Game Boy (that GB adapter for the SNES) would cause the games to send color commands to the SGB/SNES, coloring the screen.

Try setting your emulator to SGB mode and see if that works.

**Comment by mattmills49** [comment]
Thank you for your thorough reply! I wasn't able to get OpenEMU to use SGB mode, some basic searches didn't make it seem possible, but I switched to the KiGB emulator and that seemed to work! Thanks again.
