### ISSUE TITLE
Two small suggestions

### ISSUE THREAD

**Issue by eisnerguy1** [Rangi42/redstarbluestar#6]
Trying to reset my password so I can leave a comment on the [Pokémon Red★ and Blue★: Space World Edition](https://hax.iimarckus.org/topic/7470/) topic  but, I just wanted to say thanks.  I was in the process of starting something like this hack and your version is much better than anything I would've been able to achieve.  I'm happy that I came across it.

I did have 2 small requests/ideas:

*If you're going with the whole "Spaceworld 1997" theme, perhaps include [the Oak sprite from that demo](https://github.com/pret/pokegold-spaceworld/blob/master/gfx/trainer/oak.png)
![prof oak](https://user-images.githubusercontent.com/3295271/96524286-d295ad00-1245-11eb-9c9a-c41f58f5980b.png)

*Perhaps include the full Pokémon status screen from the Spaceworld 1997 demo?  As it stand now, all the information feels a little cramped.

This versus what's offered in the actual demo:
![redstar-0](https://user-images.githubusercontent.com/3295271/96524729-0e7d4200-1247-11eb-8993-0791d4503fbc.png) ![redstar-1](https://user-images.githubusercontent.com/3295271/96524730-0e7d4200-1247-11eb-8a69-6b2d355bd5d7.png)
![mew_sw_97_1](https://user-images.githubusercontent.com/3295271/96524807-43899480-1247-11eb-947c-a29e6033b0b4.png) ![mew_sw_97_2](https://user-images.githubusercontent.com/3295271/96524808-44222b00-1247-11eb-83e5-263ac7ff60ce.png) ![mew_sw_97_3](https://user-images.githubusercontent.com/3295271/96524809-44222b00-1247-11eb-85bb-3788a3a63d3d.png)

Those are the only things that I could think of that would improve this already awesome hack :D

**Comment by Rangi42** [comment]
Thanks, I'm surprised Oak wasn't in already! As for the stats screen, I may add that, although it would be a vertical layout like English GSC, and would involve some more significant code changes.

**Comment by eisnerguy1** [comment]
No worries!  Like, I was actually working on this exact idea.  I was emailing back and forth with Danny-E 33 the past few days.  Now that I think about it, I may have seen the [Pokécommunity topic](https://www.pokecommunity.com/showthread.php?t=409459) shortly after the Spaceworld demos leaked and didn't make the connection until now XD.  Anyhoo, this is leaps and bounds beyond what I could've accomplished so, thanks!
