### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by eisnerguy1** [Rangi42/redstarbluestar#7]
Ok, I lied, I had 1 other suggestion:

Perhaps and an option to build a debug Blue rom like the [Pret GitHub offers](https://github.com/pret/pokered)?  
Oh wow, just realized those were your Blue debug support commits on that.  Awesome job on that.  Super cool to see how things work :D

**Comment by Rangi42** [comment]
Yeah, that would be neat. I would go ahead and make holding B walk through walls, not just disable encounters; although it wouldn't have SW97's "bounce off the edge of the map" effect. (Collision behaviors in Gen 1 are an incoherent mess, there's no single system.)

**Comment by eisnerguy1** [comment]
Doesn't surprise me considering how many bugs/other issues were in Gen 1 XD

Oh, another thing I came across.  In both games, I already have the Pokémon menu item listed before I get my first Pokémon.  I just built the source code and didn't modify anything.

**Comment by Rangi42** [comment]
That's normal.

**Comment by eisnerguy1** [comment]
Ah, you're right.  It's been forever since I've actually played Red/Blue and not gone straight into the tall grass at the start :P
