### ISSUE TITLE
Battle Tent

### ISSUE THREAD

**Issue by Hitomi98** [Rangi42/redstarbluestar#9]
Hi, this is not really a bug or issue.
I was just wondering if there are any plans to add a battle tent to this rom hack like in the Pokemon Red Anniversary (TPP) Rom Hack.
Or if this is even possible.
This hack is perfect, and I thought some thing like that (post-endgame) would be amazing :)

**Comment by FredrIQ** [comment]
I never actually played Anniversary Red (only AC) but my understanding from a bit of googling is that it's basically the Battle Tower? Polished features the Battle Tower already. It is also modernized to work like modern iterations of it (closest approximation is the HGSS Battle Tower) as opposed too the original Crystal BT.

**Comment by Rangi42** [comment]
The Battle Tower in Johto and postgame Battle Factory in Kanto play this role.

**Comment by JustRegularLuna** [comment]
tfw yall were both replying as if this was an issue on polished crystal but its an issue on RedStar/BlueStar though and that doesnt have Johto or a Battle Tower or whatever

**Comment by Rangi42** [comment]
Oh, lol. Red★/Blue★ is complete though, unless even more prototype content leaks. (Not going to happen.)
